name: Master Workflow

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Run Tests in Docker
        run: |
          docker build --target test -t my-app:test .
          docker run --rm my-app:test