name: Master Workflow

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          docker build --target test -t my-app:test .
          docker run --rm my-app:test
  
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run Lint Checker
        run: |
          docker build --target lint -t lint:check .
          docker run --rm lint:check